# site properties and page defaults
title: Bone Lab
subtitle: Join us
description: Bone Kuromi Cola
header: images/background.png.jpg
footer: images/background.png.jpg
proofer: false

# site social media and other links
links:
  email: jiamingsmu1333@smu.edu.cn
  orcid: 0000-0001-8520-566X
  google-scholar: https://scholar.google.com/citations?hl=en&user=SiSF35EAAAAJ
  

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
