- id: doi:10.1186/s12951-023-02050-7
  type: paper
  description: Amazing Research
  image: images/hydro.jpg 

- id: doi:10.1016/j.canlet.2024.216658 
  type: paper
  image: images/cancerletter.jpeg

- id:  doi:10.1016/j.jagp.2023.08.001
  type: paper
  image: images/AJGP.png

- id: doi:10.1172/jci.insight.161932
  type: paper
  image: https://df6sxcketz7bb.cloudfront.net/volumes/10/15/10-15-cover.jpg
  
- id: doi:10.1007/s42114-023-00673-w
  type: paper
  image: https://media.springernature.com/w316/springer-static/cover-hires/journal/42114?as=webp
  
- id: doi:10.1007/s42114-023-00649-w
  type: paper
  image: https://media.springernature.com/w316/springer-static/cover-hires/journal/42114?as=webp

- id: doi:10.3389/fimmu.2022.1065739
  type: paper
  image: images/front.png
  
- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg

- id: doi:10.1007/s00586-022-07389-3
  type: paper
  image: https://media.springernature.com/w316/springer-static/cover-hires/journal/586?as=webp

- id: doi:10.3389/fphys.2022.974266
  type: paper
  image: images/front.png

- id: doi:10.3390/ijms23169253
  type: paper
  image: https://pub.mdpi-res.com/img/journals/ijms-logo.png?41930e44070e4940

- id:  doi:10.1302/2046-3758.116.BJR-2021-0436.R1
  type: paper
  image: https://boneandjoint.org.uk/images/BJR_logo.svg
  
- id: doi:10.1016/j.arr.2022.101608
  type: paper
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1568163721X0013X-cov150h.gif

- id:  doi:10.1016/j.trechm.2022.02.002
  type: paper
  image: https://www.cell.com/cms/asset/96c3e337-2269-46bb-8010-0e36627fe903/cov200h.gif

- id: doi:10.1302/2046-3758.114.BJR-2021-0192.R1
  type: paper
  image: https://boneandjoint.org.uk/images/BJR_logo.svg

- id: doi:10.3389/fgene.2022.821508
  type: paper
  image: images/front.png
 
- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg  

- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg

- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg

- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg

- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg

- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg

- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg

- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg

- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg

- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg

- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg

- id: doi:10.1002/advs.202203718
  type: paper
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/2eba278e-8e57-4af8-86d9-5cf5e120c5f1/advs.v10.3.cover.jpg  
