- id: doi:10.1186/s12951-023-02050-7
  type: paper
  description: Amazing Research
  image: images/hydro.jpg
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: doi:10.1016/j.canlet.2024.216658
  image: images/cancerletter.jpeg

- id:  doi:10.1016/j.jagp.2023.08.001
  image: images/AJGP.png

- id: doi:10.1007/s42114-023-00673-w
  image: images/advancecom.jpeg
  
- id: doi:10.1007/s42114-023-00649-w
  images: images/advancecom.jpeg
  
